app/kijatek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'core'  # here for namespacing of urls.

urlpatterns = [
    path("", views.home_page, name="home"),
    path("search/data=<bac_plus>+<discipline>+<city>", views.search_info, name="search_info"),
    path("establishments/data=<establishment_id>", views.search_establishment, name="search_establishment"),
    path("all-establishments/", views.all_establishments, name="all_establishments"),
    path("establishments/departments/data=<establishment_id>+<department_id>", views.search_department, name="search_department"),
    path("establishments/all-departments/", views.all_departments, name="all_departments"),
    path("test", views.test, name="test"),
]

kijatek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # user management
    path('accounts/', include('allauth.urls')),
    
    # local apps
    path('', include('core.urls')),
]

templates/department.html
{% extends 'header.html' %}
{% load static%}
{% block css%}
<link rel="stylesheet" href="{% static 'core/css/comments.css'%}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row-12">
        <div class="col-2">

        </div>
        <div class="col">
            <h5>General info:</h5>
            <div class="border alert-info">
            <ul>
                <li>{{department.name}} is a department of {{department.establishment.name|lower}} AKA {{department.establishment.abreviated_name}} that offers a trining in {{department.discipline.name}}.
                </li>
                <li>required level of studies: bac {%if department.bac_plus < 0 %}
                    {{department.bac_plus}}
                    {% else %}
                    + {{department.bac_plus}}
                    {% endif %}
                </li>

                <li>Ending this training will give you the grad: {{department.grad}}
                </li>
            </ul>
            </div>

            <div class="p mt-5">
                <div class="h5 font-weight-bold">
                    More about:
                </div>
                <div class="p lead">
                    {{department.description}}
                    {% lorem 5 p %}
                </div>
                
            </div>
                       
        </div>
        <div class="col-3 bg-dark">

        </div>
    </div>
    <div id="code-snippet">
        <div class="h4 mt-5 badge-primary text-center">Students feedback</div>
        <div class="row">
            <div class="col-12">
            <div class="blog-comment">
                <hr/>
                <!--for comment reply-->
                {%for comment, replies in comments_replies.items%}
                <ul class="comments">
                    <li class="clearfix">
                    <img src="" class="avatar" alt="">
                    <div class="post-comments">
                        <p class="meta">date hna <a href="#">useraname</a> says : <i class="pull-right"><a href="#"><small>Reply</small></a></i></p>
                        <p>
                            {{comment.body|safe}}
                        </p>
                    </div>
                    <!--for replies-->
                    {% for reply in replies%}
                        <ul class="comments">
                            <li class="clearfix">
                                <img src="" class="avatar" alt="">
                                <div class="post-comments">
                                    <p class="meta">Dec 12, 2014 <a href="#">JohnDoe</a> says : <i class="pull-right"></a></i></p>
                                    <p>
                                        {{reply.body|safe}}
                                    </p>
                                </div>
                            </li>
                        </ul>
                    {% endfor %}
                    <!--for replies-->
                    </li>
                </ul>
                {% endfor %}
                <!--for comment reply-->         
            </div>
        </div>
            
        </div>
        <!--row of comment-->
        <div class="row">
            <div class="col-7 offset-3">
                <form method="POST" role="form">
                    {% csrf_token %} 
                    <div class="form-group" id='main'>
                        <label for="exampleFormControlTextarea1">Add comment</label>
                        {{comment_form.comment}}
                    
                    
                        <button type="submit" class="btn btn-outline-success">Click to add</button>
                    </div>
                </form>
            </div>
        </div>
        <!--end of row of comment-->
        </div>
    </div>

{% endblock %}

templates/departments.html
{% extends 'header.html' %}


{% block title %}
<title>Unknown</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    
    <div class="h4 mb-4">
    {%if not for_all%}
        <div class="alert alert-secondary text-center mb-4">
        
            You are in bac
            {% if info.bac_plus >= 0 %}
            {{ info.bac_plus }}
            {% else %}
            +  {{ info.bac_plus }}
            {% endif %}
            want to study
            {{info.discipline.name}}
            in 
            {{info.city.name}}
        </div>
    {%endif%}
    </div>
    
    {% if departments %}
    <div class="h6 font-weight-bold mb-4">Here is what we found for you:</div>
    <div class="row">
        {% for d in departments %}
        <div class="card border-primary m-2" style="width: 22rem;">
            <div class="card-body">
                <h5 class="card-title">{{d.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{d.establishment}}</h6>
                <p class="card-text">{{d.description}}</p>
                <a href="{% url 'core:search_department' d.establishment.id d.id %}" class="card-link">See department</a>
                <a href="{% url 'core:search_establishment' d.id %}" class="card-link">See establishment</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {%else%}
        <div class="h5 text-danger mt-5"> Sorry we don't have any info about your query yet</div>
    {% endif %}
    

</div>

{% endblock %}

templates/establishment.html
{% extends 'header.html' %}

{%load static%}

{% block css %}
<link href="http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.css" rel="stylesheet" type="text/css">
<link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.css" rel="stylesheet" type="text/css">
{% endblock %}


{% block title %}
<title>{{establishment.abreviated_name}}</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">

    <div class="col-9">
        <div class="alert-info text-center">
            <p class=" h4 mb-2">{{establishment.name}}</p>
            <p class=" h5">is a {{establishment.establishment_type|lower}} school,
                also known as {{establishment.abreviated_name}}
                <br>
                directed now by {{establishment.director}}
                <br>
                <!--map icon-->
                <i style='font-size:24px' class='fas'>&#xf3c5;</i> 
                <!--end map icon-->
                {{establishment.adress}}, {{establishment.city}}
                <br>
                phone: {{establishment.phone}}
                <br>
                website: {{establishment.website}}
            </p>
        </div>
        
        <div id="establishmentDescription" class="p lead">
            <div class="h4 font-weight-bold mt-3"> description:</div>
            <br>
            {{establishment.description}}
            {% lorem 2 p %} {#hadi ghi paragraph mafiha nfe3#}

        </div>

        <div id="establishmentDescription" class="p mt-5">
            <div class="h4 font-weight-bold mt-3"> Departments:</div>
            <br>
            <ul class="list-group">
                {% for d in departments  %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{d.name}}
                    <a href="{% url 'core:search_department' establishment.id d.id %}">
                    <span class="badge badge-primary badge-pill">See department</span>
                    </a>
                </li>
                {% endfor %}

        </div>
        <!--############## bokeh chart ################-->
        <div class="row">
            <div class="h4 font-weight-bold mt-5 mb-4"> Sentimental chart of students opinions:</div>
            {{ div | safe }}

        </div>
        


    </div>
    <div class="col-3 bg-dark">
        <!--this is for adds-->
        
    </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js"></script>
<script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.js"></script>
{{ script | safe }}
{% endblock %}

templates/establishments.html
{% extends 'header.html' %}


{% block title %}
<title>Unknown</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    
    <div class="h4 mb-4">
       <!-- empty div-->
    </div>
    
    {% if establishments %}
    <div class="h6 font-weight-bold mb-4">Here is available establishments:</div>
    <div class="row">
        {% for e in establishments %}
        <div class="card border-primary m-2" style="width: 22rem;">
            <div class="card-body">
                <h5 class="card-title">{{e.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{e.establishment}}</h6>
                <p class="card-text">{{e.description}}</p>
                <a href="{% url 'core:all_establishments'%}" class="card-link">See establishment</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {%else%}
        <div class="h5 text-danger mt-5"> Sorry we don't have any info about your query yet</div>
    {% endif %}
    

</div>

{% endblock %}

templates/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.css'%}" rel="stylesheet" id="bootstrap-css">
    <!--<link rel="stylesheet" href="{% static 'core/css/index.css'%}">-->

    <!--css only added for a pecific template-->
    {% block css %}
    {% endblock %}
    <!--###############################-->

    <link rel="stylesheet" href="{% static 'core/css/header.css'%}">
    <script src="{% static 'core/js/social-media-fonts.js'%}"></script>

    <!--title a pecific template-->
    {% block title %}
    {% endblock %}
    <!--########################-->
</head>

<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Search <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:all_establishments' %}">Establishments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:all_departments' %}" tabindex="-1">Departments</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Disciplines
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
  
          <nav class="my-2 my-md-0 mr-md-3">
            {% if user.is_authenticated %}
              <a class="btn btn-outline-danger" href="{% url 'account_logout' %}">Log Out</a>
            {% else %}
              <a class="btn btn-outline-success" href="{% url 'account_login' %}">Log In</a>
              <a class="btn btn-outline-primary"href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}
          </nav>

          
        </div>
      </nav>


    </div>

    {% block content %}
    {% endblock %}

    <div id="footer-area" class="container-fluid mt-5">

    <!-- Footer -->
    <section id="footer">
      <div class="container-fluid">
        <div class="row text-center text-xs-center text-sm-left text-md-left">
          <div class="col-xs-12 col-sm-4 col-md-4">
            <h5>Quick links</h5>
            <ul class="list-unstyled quick-links">
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Videos</a></li>
            </ul>
          </div>
          <div class="col-xs-12 col-sm-4 col-md-4">
            <h5>Quick links</h5>
            <ul class="list-unstyled quick-links">
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Videos</a></li>
            </ul>
          </div>
          <div class="col-xs-12 col-sm-4 col-md-4">
            <h5>Quick links</h5>
            <ul class="list-unstyled quick-links">
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
              
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
            <ul class="list-unstyled list-inline social text-center">
              <li class="list-inline-item"><a href="javascript:void();"><i class="fab fa-facebook"></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();"><i class="fab fa-twitter-square"></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();"><i class="fab fa-instagram"></i></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();"><i class="fab fa-google-plus"></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
            </ul>
          </div>
          </hr>
        </div>	
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
            <p><u><a href="#">Kijatek</a></u> is a Registered idea of Ali Khyar. Was realized as school project for uemf with the supervision of Teacher Habib </p>
            <p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="#" target="_blank">Kijatek</a></p>
          </div>
          </hr>
        </div>	
      </div>
    </section>
    <!-- ./Footer -->
    </div>
    <script src="{% static 'core/js/jquery-3.4.1.min.js'%}"></script>
    <script src="{% static 'core/js/popper.js'%}"></script>
    <script src="{% static 'core/js/bootstrap.min.js'%}"></script>
    {% block js %}
    {% endblock %} 

</body>

</html>

templates/home.html
{% extends 'header.html' %} 
{%load static%} 
{% block css %}
<link rel="stylesheet" href="{% static 'core/css/home.css'%}" />
{% endblock %} 
{% block title %}
<title>Home</title>
{% endblock %} 
{% block content %}

<div id="search-area mt-0" class="container">
  <!-- #####################3 carousel #####################3-->

  <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-interval="300">
        <img src="{% static 'core/images/ban.jpg'%}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval="2000">
        <img src="{% static 'core/images/ban2.jpg'%}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'core/images/ban3.jpg'%}" class="d-block w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="mt-5">
    <!--empty div-->
  </div>

  <!-- ################## end carousel #####################3-->
  <div class="row-cols-12" id="index-content">
    <form method="post" role="form">
      {% csrf_token %}
      <!-- ####### first row for leve/want to continue in/ city########## -->
      <div class="row" id="row-choose">
        <div class="col">
          <select name="bac_plus" class="browser-default custom-select">
            <option selected>your level</option>
            <option value="-1">Bac-</option>
            <option value="0">Bac</option>
            <option value="2">Bac+2</option>
            <option value="3">Licence/Bachelor</option>
            <option value="4">Master</option>
            <option value="5">Phd</option>
          </select>
        </div>
        <div class="col">
          <select name="discipline" class="browser-default custom-select">
            <option selected>want to continue in</option>
            {% for discipline in disciplines %}
            <option value="{{discipline.id}}">{{discipline.name}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col">
          <select name="city" class="browser-default custom-select">
            <option selected>city</option>
            {% for city in cities %}
            <option value="{{city.id}}">{{city.name}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <!-- ####### end first row ########## -->

      <input
        class="btn btn-primary btn-lg btn-block mt-4"
        type="submit"
        value="Submit"
      />
    </form>
  </div>
</div>

{% endblock %}

templates/khliha.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <!--
<div class="col mt-2">
                <form>
                  <label class = "checkbox-inline">
                    <input type = "checkbox" value = "">Public
                  </label>
                  <label class = "checkbox-inline">
                    <input type="checkbox" value="">Private
                  </label>
                  <label class = "checkbox-inline">
                    <input type = "checkbox" value = "">Semi
                  </label>
                </form>
             </div>

-->
</body>
</html>

templates/search_info.html
{% extends 'header.html' %}


{% block title %}
<title>Search</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    
    <div class="h4 mb-4">
    <div class="alert alert-secondary text-center mb-4">
    
        You are in bac
        {% if info.bac_plus >= 0 %}
         {{ info.bac_plus }}
        {% else %}
         +  {{ info.bac_plus }}
        {% endif %}
        want to study
        {{info.discipline.name}}
        in 
        {{info.city.name}}
    </div>
    </div>
    
    {% if departments %}
    <div class="h6 font-weight-bold mb-4">Here is what we found for you:</div>
    <div class="row">
        {% for d in departments %}
        <div class="card border-primary m-2" style="width: 22rem;">
            <div class="card-body">
                <h5 class="card-title">{{d.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{d.establishment}}</h6>
                <p class="card-text">{{d.description}}</p>
                <a href="{% url 'core:search_department' d.establishment.id d.id %}" class="card-link">See department</a>
                <a href="{% url 'core:search_establishment' d.id %}" class="card-link">See establishment</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {%else%}
        <div class="h5 text-danger mt-5"> Sorry we don't have any info about your query yet</div>
    {% endif %}
    

</div>

{% endblock %}

templates/test.html
{% extends 'core/header.html' %}
{%load static%}

{% block css %}
<link href="http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.css" rel="stylesheet" type="text/css">
<link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}
<title>Home</title>
{% endblock %}

{% block content %}

{{ div | safe }}
        
{% endblock %}

{% block js %}
<script src="http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js"></script>
<script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.js"></script>
{{ script | safe }}
{% endblock %}

templates/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hiiiiiiiiii 222222222222</h1>
    
</body>
</html>